### ISSUE TITLE
met a error when excute the mt example

### ISSUE THREAD

**Issue by jcfeng** [pmichel31415/teapot-nlp#3]
hi  I met the error when  excute the mt example in your example,could you please give me some hint how to fix it ?
Traceback (most recent call last): File "xxx/software/Anaconda3/bin/teapot", line 11, in <module> load_entry_point('teapot-nlp==0.2.1', 'console_scripts', 'teapot')() File "xxx/software/Anaconda3/lib/python3.7/site-packages/teapot_nlp-0.2.1-py3.7.egg/teapot/main.py", line 168, in main s_src_avg, s_src_std, s_src_5, s_src_95 = utils.stats(s_src) File "xxx/software/Anaconda3/lib/python3.7/site-packages/teapot_nlp-0.2.1-py3.7.egg/teapot/utils.py", line 23, in stats x = sorted(x) TypeError: '<' not supported between instances of 'CHRF' and 'CHRF'

**Comment by pmichel31415** [comment]
Hi @jcfeng thanks for reporting this. Looks like this was caused by BC breaking changes in recent versions of sacrebleu. My latest commit on master should have fixed it, try running the example again with the latest version (if you are installing from pypi it might take some time to update to the latest version, if you're in a hurry install from github directly). Let me know if the issue persists.

Cheers

**Comment by jcfeng** [comment]
> Hi @jcfeng thanks for reporting this. Looks like this was caused by BC breaking changes in recent versions of sacrebleu. My latest commit on master should have fixed it, try running the example again with the latest version (if you are installing from pypi it might take some time to update to the latest version, if you're in a hurry install from github directly). Let me know if the issue persists.
> 
> Cheers

I used the latest code and the bug is fixed,thanks!
